# Site
name: "Gaceta Eorzea"
title: "Gaceta Eorzea"
description: "Artículos y guías de Final Fantasy XIV en Español."
logo: 'assets/images/log.png'
favicon: 'assets/images/logo.png'
google_analytics: 'G-Z6JRH15CR6'
disqus: 'https-gaceta-eorzea-com'
mailchimp-list: 'https://xxxx'
include: ["_pages"]
permalink: /:title/
lang: "es_ES"
locale: "es_ES"
social:
  name: Gaceta Eorzea
  links:
    - https://twitter.com/BenBalter  
# Authors
authors:
  cecile:
    name: Cecile
    display_name: Cecile
    avatar: 'assets/images/avatars/cucute.jpg'
    email: jamedina@gmail.com
    web: https://www.juan-medina.com
    twitter: https://twitter.com/JuanMedinaCode
    description: "Tecnólogo y amante de de los videojuegos, sobre todo los MMOs. Juego en Ragnarok (Chaos) con Cucute Cute"
  sharn:
    name: J0HNyRISu
    display_name: J0HNyRISu
    avatar: 'assets/images/avatars/jony.jpg'
    email: risugamer@gmail.com
    twitter: https://twitter.com/J0HNyRISu
    description: "Jugador de MMos y JRPGs. Awakener of the Void en Wraeclast. Traveler for Tamriel. Brujo y Adalid DOVAKHIIN. For The Horde! Sharn Fafnirson en Ragnarok (Chaos)" 
  ulthar:
    name: Ulthar Hanzo
    display_name: Ulthar
    avatar: 'assets/images/avatars/ulthar.jpg'
    description: "Jugador de videojuegos y programador a ratos"   
  zex:
    name: Zex Krow
    display_name: Zex Krow
    avatar: 'assets/images/avatars/zex.jpg'
    twitter: https://twitter.com/ensabe95
    description: "Jugador de ff14 con el objetivo de dar a conocer el juego a mas gente y ayudar a nuevos jugadores"
  aryn:
    name: Aryn XIV
    display_name: Aryn XIV
    avatar: 'assets/images/avatars/aryn2.jpg'
    email: arynxiv@gmail.com
    web: https://www.youtube.com/channel/UCLgSQnV6of5-0x568qWilNw
    twitter: https://twitter.com/Aryn_XIV
    description: "Creador de contenido de Lore y Teorías de FFXIV en Youtube. Intentando acercar el lore de FFXIV a la comunidad Española."
  lia:
      name: Lia Tales
      display_name: Lia Tales
      avatar: 'assets/images/avatars/lia.jpg'
      email: liatalesffxiv@gmail.com
      web: https://www.twitch.tv/lia_tales
      twitter: https://twitter.com/LiaTales_ffxiv
      description: "Housing Savage FTW"    
  hers:
      name: Hers
      display_name: Hers
      avatar: 'assets/images/avatars/hers.jpg'
      email: rrasgas@gmail.com
      twitter: https://twitter.com/Herstryp
      description: "Jugador de RPGS con una adicción a gachas y MMOs"   
  borja:
      name: Borjalos Sopabuena
      display_name: Borjalos Sopabuena
      avatar: 'assets/images/avatars/borja.jpg'
      twitter: https://twitter.com/Borjalos
      description: "Un random que juega, se divierte y grita mucho."         
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, build.bat, docs, tmp]

default_locale: "es"